version: '3.7'
services:
  # БАЗА ДАННЫХ
  db:
    image: "postgres"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"

  # БЭКЕНД
  backend:
    build: backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - backend/.env

  # ФРОНТЕНД
  frontend:
    build: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - frontend/.env


