version: '3.7'
services:
  # БАЗА ДАННЫХ
  data_base:
    image: "postgres"
    container_name: data_base
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"

  # БЭКЕНД
  backend:
    build: backend
    container_name: backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "8443:8443"
    depends_on:
      - data_base


  # ФРОНТЕНД
  frontend:
    build: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - frontend/.env


